// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXKyfF9JlFawvT_mQ1BPu-9LYHU0hNN_8',
    appId: '1:129489483073:web:97a13b18ae4bf2d8f3ddc0',
    messagingSenderId: '129489483073',
    projectId: 'flash-chat-5e59c',
    authDomain: 'flash-chat-5e59c.firebaseapp.com',
    storageBucket: 'flash-chat-5e59c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtRjK2WUZK1u-j_XTQs_NB0-ut12Txfw',
    appId: '1:129489483073:android:207dfb8dc7593833f3ddc0',
    messagingSenderId: '129489483073',
    projectId: 'flash-chat-5e59c',
    storageBucket: 'flash-chat-5e59c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxVP6QI5A_kBh6-9QtcQTTRExU8Y9oLQ',
    appId: '1:129489483073:ios:fe9e888618cd2472f3ddc0',
    messagingSenderId: '129489483073',
    projectId: 'flash-chat-5e59c',
    storageBucket: 'flash-chat-5e59c.appspot.com',
    iosBundleId: 'com.example.flashChatNew',
  );
}
